# site settings
title: Angel Torres
subtitle:
email: hello@angeltorr.es
description: Passionate about design and technology.
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Escondido
state: CA
zip_code: 92025
country: United States of America
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/angltrs
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/angeltorr.es
linkedin_url: https://www.linkedin.com/in/angeltorresc
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
